# This is a GitLab CI/CD configuration file for AngstromCube

stages:     # List of stages for jobs, and their order of execution
  - build
  - test
  - run

build_on_JUSUF:
  stage: build
  script:
    - echo "Set module environment"
    - module --force purge && module load Stages/2023  GCC/11.3.0  ParaStationMPI/5.8.0-1-mt imkl-FFTW/2022.1.0 CMake 
    - export MKL_ROOT=/p/software/jusuf/stages/2023/software/imkl/2022.1.0/mkl/latest/
    - echo "Start build system..."
    - rm -rf build && mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/a43
    - echo "Compiling the code..."
    - make -j install
    - cd ..
    - echo "Compile complete."
    - ls ~/a43/lib64 ~/a43/bin
  tags:         # Set tags such that we can use the shared runners of the JSC gitlab
    - jacamar
    - jusuf 
    - login     # Compile on login node
    - shell

test_on_JUSUF:
  stage: test
  script:
    - echo "Run A43 unit tests..."
    - module --force purge && module load Stages/2023  GCC/11.3.0  ParaStationMPI/5.8.0-1-mt imkl-FFTW/2022.1.0 CMake 
    - pwd
    - ls ~/a43/lib64 ~/a43/bin
    - cd test
    - mkdir -p pot # directory for the Zeff.00Z files
    - rm -f                                    atoms.xyz
    - echo "1"                               > atoms.xyz
    - echo "#cell 2.277 2.277 2.277 p p p"  >> atoms.xyz
    - echo "Cu 0 0 0"                       >> atoms.xyz
    - echo "# 16 x 16 x 16" > vtot.dat
    - ~/a43/bin/a43 --test
    - cd ..
    - echo "A43 unit tests done."
  tags:
    - jacamar
    - jusuf 
    - login
    - shell

run_on_JUSUF:
  stage: run
  script:
    - echo "Run green unit tests..."
    - module --force purge && module load Stages/2023  GCC/11.3.0  ParaStationMPI/5.8.0-1-mt imkl-FFTW/2022.1.0 CMake 
    - pwd
    - ls ~/a43/lib64 ~/a43/bin
    - ~/a43/bin/green --test
    - echo "green unit tests done."
  tags:
    - jacamar
    - jusuf 
    - login    # ToDo Run other tests on backend --> change to compute
    - shell    # ToDo Run other tests on backend --> change to slurm
